# Generated by Django 3.1.1 on 2020-09-19 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200919_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 8, 35, 53, 181755, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
